### ISSUE TITLE
Remover a camada de certificados

### ISSUE THREAD

**Issue by zarathon** [npi-ufc-qxd/contest#160]
Remover a camada de geração de certificados, no seu lugar deverá ser disponibilizado os dados em csv ou ods (planilha), ver qual a melhor estratégia.

**Comment by zarathon** [comment]
Dados a serem considerados na exportação: Nome do Autor, Nome dos Coautores (inline), Titulo do Trabalho, Data final do Evento. Caso surja outros campos, os senhores serão avisados

**Comment by northEXE** [comment]
Teste de certificados do evento:
01 - Entrei no sistema como organizador;
02 - Entrei no evento "Evento de Teste 3";
03 - Em detalhes do evento, tem uma barra de menu com quatro opções: "Meus Eventos", "Eventos Ativos", "Eventos Inativos" e "Certificados";
04 - Fui na barra de menu, na opção "Certificados";
05 - Selecionei a opção Certificados para Organização*;
06 - Apareceu uma tela*** com o nome dos organizadores, selecionei a opção com o nome dos organizadores. No caso, só havia um;
07 - Apertei o botão de Gerar PDF;**
08 - Foi feito um download de uma planilha com o nome dos organizadores, no caso, só um nome apareceu
09 - Ainda no login de organizador, e continuando no "Evento de Teste 3", novamente na tela de "Detalhes do evento", na barra de menu, novamente na opção de Certificados, selecionei "Certificados para Revisores"*;
10 - Aparece a tela*** com nome dos revisores do trabalho para selecionar e gerar a planilha, apertando no botão Gerar PDF;**
11 - Novamente foi gerada uma planilha com o nome dos revisores. No caso, só um nome apareceu;
12 - Voltando para a tela "Detalhes do Evento", ainda no "Evento de Teste 3", fui novamente na opção "Certificados", desta vez, selecionando a opção "Certificados para Trabalhos"*;
13 - Apareceu uma tela*** com a opção de marcar os trabalhos para ser gerada a planilha com o certificado;
14 - Selecionando o nome presente, apertei o botão "Gerar PDF"**, para ser gerada a planilha;
15 - Apareceu uma planilha com as informações do trabalho, que são: "Nome", "Coautores", "Título" e "Data";

Observações:

*Foi observado que nas opções do menu "Certificados para... ", será necessário uma refatoração no rótulo das opções, que será modificado para "Certificado em planilha para... ";

**No botão para gerar o certificado, apesar de estar gerando planilhas,  está escrito no rótulo "Gerar PDF". Será necessário uma refatoração, modificando o rótulo para "Gerar Planilhas";

***Em ambas as telas, os títulos delas são: "Gerar Certificados Dos Trabalhos", onde na tela de certificados de origanizadores deveria aparecer "Gerar Certificados dos Organizadores" e na tela de gerar certificados dos revisores deveria aparecer "Gerar certificados dos Revisores". Já na tela de certificados de trabalhos, o título está correto, pois nessa tela, é onde são gerados os certificados dos trabalhos; 

Na tela "Gerar Certificado dos Trabalhos", se não houver nenhum trabalho para ser selecionado, não há nenhum aviso de que não há trabalhos a serem selecionados, e o botão para gerar a planilha ainda continua habilitado. Apertando o botão, vai para uma tela de erro com o aviso: "Arquivo ou recurso não encontrado(" e um botão "Voltar". Será necessário uma refatoração que conserte esse problema, para que quando não haja um trabalho para gerar certificado, dê um aviso, e o botão não esteja habilitado. O mesmo ocorre com um evento que ainda não tem um revisor. O botão ainda fica presente, mesmo sem nenhum revisor atribuído. A tela de erro traz a seguinte informação: "Erro inesperado no sistema. Tente novamente mais tarde" e um botão "Voltar". Da mesma maneira, deve ser feita uma refatoração para que o botão seja desabilitado quando não haja nenhum revisor atribuído.
![01_TESTE_LOGIN_ORGANIZADOR-TELA_EVENTO.png](https://zube.io/files/npi-ufc-qxd/192668a1a088e290b1d30c1bf4018f9e.png)
![02_TELA_EVENTO_DETALHES_EVENTO.png](https://zube.io/files/npi-ufc-qxd/56e2fdb5fb7effaa1ed8d1e512856ea0.png)
![03_TELA_DETALHES_OPCAO_GERAR_CERTIFICADO_ORGANIZADOR.png](https://zube.io/files/npi-ufc-qxd/f255e6de89e8a636400f2cb8c66d917a.png)
![04_TELA_GERAR_CERTIFICADO_ORGANIZADOR.png](https://zube.io/files/npi-ufc-qxd/67bb615f29cc9f90c49cab7456ceead6.png)
![05_TELA_CERTIFICADO_PLANILHA_ORGANIZADOR.png](https://zube.io/files/npi-ufc-qxd/82d19d563d94817d9ad120fd9b8f0626.png)
![06_TELA_DETALHES_OPCAO_GERAR_CERTIFICADO_REVISOR.png](https://zube.io/files/npi-ufc-qxd/bdbe76ba47231743f40ee556265ffa25.png)
![07_TELA_GERAR_CERTIFICADO_REVISOR.png](https://zube.io/files/npi-ufc-qxd/8b3664c355fde3250be7ab58fc7c5419.png)
![08_TELA_CERTIFICADO_PLANILHA_REVISOR.png](https://zube.io/files/npi-ufc-qxd/2467c66c4fa6bcd62ca164005748a0ed.png)
![09_TELA_DETALHES_OPCAO_GERAR_CERTIFICADO_TRABALHO.png](https://zube.io/files/npi-ufc-qxd/6d26635380deae0f1eb500689e7bbdf2.png)
![10_TELA_GERAR_CERTIFICADO_TRABALHO.png](https://zube.io/files/npi-ufc-qxd/cc2ed0183eb1f5a03ebdf268caaf53e2.png)
![11_TELA_CERTIFICADO_PLANILHA_TRABALHO.png](https://zube.io/files/npi-ufc-qxd/9f63882a8c74a62004143db688e12ec7.png)
![12_TELA_GERAR_CERTIFICADO_SEM_TRABALHO.png](https://zube.io/files/npi-ufc-qxd/6a20a4f08f616f963319808b732c52c5.png)
![13_TELA_ERRO_SEM_TRABALHO.png](https://zube.io/files/npi-ufc-qxd/6fad07b9a732cc77ee70e7d7306d44a8.png)
![14_TELA_GERAR_CERTIFICADO_SEM_REVISOR.png](https://zube.io/files/npi-ufc-qxd/36b42c1063d5b737250f7568dff6f298.png)
![15_TELA_ERRO_SEM_REVISOR.png](https://zube.io/files/npi-ufc-qxd/d8b0be5f1a4fb27dd33a286b9ce663b8.png)
