### ISSUE TITLE
Refatorar o uso de envio de email

### ISSUE THREAD

**Issue by zarathon** [npi-ufc-qxd/contest#161]
Refatorar o uso de email para que os mesmos agora sejam enviados com a biblioteca npi-mail que está no repositório do github.

**Comment by northEXE** [comment]
Teste de email.

Obs: Como ainda não há nenhuma tela para esta funcionalidade, basicamente foi realizado um teste de caixa branca.

01 - Dentro do código, na classe "LoginController", foi chamada a classe "EnviarEmailService";
02 - Nesta classe, há um método chamado "enviarEmail", onde foram definidos os valores para o email, que são: "Título", "Assunto", "Email Destinatário" e "Corpo".*;
03 - O sistema foi colocado para executar. O email foi posto para ser enviado assim que a tela de login fosse chamada;
04 - No email que foi colocado como destinatário, foi recebido o email da forma como foi definido na linha de código.

*Como foi dito no início, ainda não há nenhuma tela que lide com isso, então, foi necessário fazer esse teste Hard Coded, definindo os valores em memória para que pudesse ver se o email estava sendo enviado corretamente.
![Captura de tela de 2017-04-18 09-06-38.png](https://zube.io/files/npi-ufc-qxd/d51626a5f0384b813a01f1c2738911d6.png)
![Captura de tela de 2017-04-18 09-11-45.png](https://zube.io/files/npi-ufc-qxd/8b36bb885471e23cf4c392608c8c483c.png)
