### ISSUE TITLE
Criar a função de cadastro

### ISSUE THREAD

**Issue by zarathon** [npi-ufc-qxd/contest#193]
O usuário externo a UFC (fora do LDAP) poderá se cadastrar através de um formulário simples.

**Comment by northEXE** [comment]
Teste de Cadastro de Seção

01 - Entrando na tela de login, temos o seguinte texto: "Caso você não seja aluno da Universidade Federal do Ceará e deseja fazer seu cadastro, _clique aqui_ e cadastre-se."

**Comment by jacquesnier** [comment]
Ao cadastrar-se o usuário será redirecionado para a tela inicial, onde fará o login.
