### ISSUE TITLE
Convidar usuário para evento

### ISSUE THREAD

**Issue by zarathon** [npi-ufc-qxd/contest#195]
Como organizador é possivel que este convide outras pessoas para participarem do evento quando este tenha o estado privado. O organizador deverá fornecer o nome, email e papel do usuário convidado, o convidado receberá um email informando-o que ele foi adicionado

**Comment by northEXE** [comment]
Teste funcional da funcionalidade convidar usuário para um evento privado por email.

01 - Para realizar essa funcionalidade, o usuário deve ser um organizador;
02 - Entrando como organizador, seleciona-se a opção "Eventos Ativos";
03 - Na tela de Eventos Ativos, um evento privado deve ser selecionado;
04 - No evento privado a ser selecionado, clica-se na opção "Detalhes";
05 - Na tela de Detalhes do evento, temos a opção "Convidar Pessoas";
06 - Logo após selecionar a opção, aparece um modal com os campos a serem preenchidos;
07 - Após os campos preenchidos o resultado esperado é que o usuário convidado receba o email, informando que ele foi convidado para o evento.
08 - Volta-se para a tela Detalhes do evento com uma mesagem de sucesso: "Sueu email foi enviado com sucesso".

A seguir, as imagens dos passos descritos:
![TELA 01.png](https://zube.io/files/npi-ufc-qxd/4705b2c15c8f261953eccdd5fcbbdf6e.png)
Imagem 01 - Sistema logado como organizador

![TELA 02.png](https://zube.io/files/npi-ufc-qxd/b995f1166c368fde41162f03c673ef8b.png)
Imagem 02 - Lista de eventos ativos do organizador

![TELA 03.png](https://zube.io/files/npi-ufc-qxd/59f3d2892689a6e7f7db7ec8f23ffd29.png)
Imagem 03 - Tela com detalhes do evento

![MODAL 01.png](https://zube.io/files/npi-ufc-qxd/e8ef034f216dcc462c42644b3a4bf210.png)
Imagem 04 - Modal com o preenchimento dos campos para o envio do email

![TELA SUCESSO.png](https://zube.io/files/npi-ufc-qxd/ac42b7dfffc7c42851a20e505b39d0d4.png)
Imagem 05 - Retorno para a tela de Detalhes do Evento com a mensagem de sucesso

![EMAIL CONVITE.png](https://zube.io/files/npi-ufc-qxd/e1029c8b89b95a61425c60b791ee6608.png)
Imagem 06 - Email recebido pelo usuário para o evento privado
