### ISSUE TITLE
Refatorar as funções do ADMIN

### ISSUE THREAD

**Issue by zarathon** [npi-ufc-qxd/contest#225]
Ajustar a página de adicionar evento e suas peculiaridades, como foco a atender as necessidades anteriores.

**Comment by gabrielmendanha** [comment]
1. Refatorar as funções de enviar e-mail, criar o emailService e tirar a lógica do controller.
2. Na página de adicionar evento, como ADMIN, o organizador do evento deve ser convidado por e-mail e não mais ser selecionado no menu dropdown.

**Comment by northEXE** [comment]
Teste funcional para convidar organizador para um novo evento via email:

01 - Entrando como organizador, entrando na opção "Adicionar Evento", presente na barra de menus na tela inicial, entra-se na tela de cadastro de um evento;
02 - Na tela de cadastro são informados os dados do evento: nome, email do organizador e descrição do evento;

A partir desse ponto, o teste irá seguir em dois fluxos diferentes, um fluxo onde o organizador é um usuário interno, de dentro da UFC, ou externo à UFC, porém já cadastrado no sistema e o outro fluxo onde o organizador é externo e precisa se cadastrar após o convite (que é enviado depois da criação de um evento). A notação será: F01.x para o 1º fluxo e F02.x para o 2º fluxo.

F01.3 -  Logo após o cadastro, o administrador é encaminhado para a tela de eventos inativos, mostrando a mensagem "Evento cadastrado com sucesso";
F01.4 - Indo para o usuário qual o evento criado foi designado para o mesmo organizar, no dashboard (ainda será testado) temos o card "Como organizador";
F01.5 - Na tela de organização, indo na opção de eventos inativos, o evento criado está lá. Na edição de dados, são definidas as datas de prazos do evento;
F01.6 - Após a edição dos eventos, o organizador é levado para a tela de eventos ativos, e lá pode se encontrar o evento criado, e com todos os seus dados.

F02.3 - Como o usuário não está previamente cadastrado no sistema, um email é mandado para o organizador logo após o cadastro do evento, para que o organizador externo (que não tenha cadastro no sistema) possa realizar seu cadastro;
F02.4 - Como dito no passo anterior, o organizador recebe o email para realização do cadastro, onde há um link que leva para a tela de cadastro do sistema, onde o usuário deve por os seus dados como: nome, CPF e senha;
F02.5 - Logo após a realização do cadastro, o sistema vai para a tela de login. Entrando com o usuário, podemos ver o dashboard, ainda sem informações, pois o mesmo ainda não realizou nada no sistema
F02.6 - Indo para os eventos inativos, podemos editar as informações do evento, para que ele possa ser ativado;
F02.7 - Após a edição dos eventos, o organizador é levado para a tela de eventos ativos, e lá pode se encontrar o evento criado.

Obs: Na tela de cadastro do evento, no campo email, o label deveria estar escrito com email do organizador;

Ainda na tela de cadastro, o campo de email não possui uma máscara de email, ou seja, se for colocado uma entrada como "123456" ou "josefrancisco", sem um formato padrão de email, ele aceita. Deve ser posta uma máscara nesse campo, para que ele apenas aceite a criação do evento, caso no campo, o email esteja preenchido corretamente;

No email enviado pelo sistema, na mensagem temos: "Digite seu nome você, você recebeu o convite para participar do evento <NOME_DO_EVENTO> como ORGANIZADOR...". Ao invés de termos "Digite seu nome", poderia estar escrito "Caro usuário..."

Como dito anteriormente, como o dashboard não está completo durante esse teste, não teve um foco nele, porém, em testes posteriores, o dashboar será testado com detalhes.

Segue em anexo, as imagens com os passos descritos:

Imagens do fluxo 01: 
![eventof1.png](https://zube.io/files/npi-ufc-qxd/59ca18a53abe1907193fe901eb227bad.png)
Imagem 01 - Cadastro de evento com um usuário existente no sistema

![eventof1_2.png](https://zube.io/files/npi-ufc-qxd/70457f6010e1c24f457551710802d1ee.png)
Imagem 02 - Cadastro de evento realizado com sucesso

![eventof1_3.png](https://zube.io/files/npi-ufc-qxd/a9a8a6bc3c996e03210eeaa548849dc5.png)
Imagem 03 - Lista de eventos inativos no usuário com o papel de organizador

![eventof1_4.png](https://zube.io/files/npi-ufc-qxd/0d1f1f157779879664376215b5ec72d6.png)
Imagem 04 - Edição do evento para que ele possa ser ativado

![eventof1_5.png](https://zube.io/files/npi-ufc-qxd/b5a1595d6d680390bc2cb3810804c663.png)
Imagem 05 - Lista de eventos ativos com o evento criado ativado

Imagens do fluxo 02:
![eventof2_1.png](https://zube.io/files/npi-ufc-qxd/7481626207a3ec159344b60dad4d682f.png)
Imagem 06 - Cadastro de evento com um usuário externo ao sistema

![eventof2_2.png](https://zube.io/files/npi-ufc-qxd/8ba7d4109d3d30195895e68401d0c20c.png)
Imagem 07 - Cadastro de evento realizado com sucesso

![eventof2_3.png](https://zube.io/files/npi-ufc-qxd/0ce81b4bcbb6e24bbc8a6f5c780d9f47.png)
Imagem 08 - Convite para organizar o evento via email, recebido pelo usuário

![eventof2_5.png](https://zube.io/files/npi-ufc-qxd/e1c815cc9bad654d744fc70827a63f67.png)
Imagem 09 - Tela de cadastro aberto pelo usuário através do email enviado pelo sistema

![eventof2_6.png](https://zube.io/files/npi-ufc-qxd/6cd9fe4706281b305746f42097c99c0b.png)
Imagem 10 - Tela inicial do usuário após o cadastro e entrada no sistema

![eventof2_7[.png](https://zube.io/files/npi-ufc-qxd/bfc51d6a7038f23f0c839e7512eb9e9b.png)
Imagem 11 - Edição de dados do evento para que ele possa ser ativado

![eventof2_8.png](https://zube.io/files/npi-ufc-qxd/d466f28e69a9929aff3a8bdb12671273.png)
Imagem 12 - Lista de eventos ativos, com o evento criado ativado
