### ISSUE TITLE
Refatorar as funções do Organizador

### ISSUE THREAD

**Issue by zarathon** [npi-ufc-qxd/contest#226]
Ajustar as funcionalidades do organizador para atender as estórias de usuários ateriormente implementadas. Atentar para que agora o mesmo possui o unico papel de USER

**Comment by northEXE** [comment]
Teste para adicionar organizadores e revisores via email em eventos públicos e privados

Esse teste segue em dois fluxos diferentes, um fluxo para evento público, e outro para evento privado.

Fluxo de evento privado:

01 - Entrando no sistema como administrador, é criado um evento, mandando email para o organizador;
02 - Logo após a criação do evento, entra-se no sistema com o organizador que foi convidado, indo para a seção de eventos inativos, o evento é ativado, porém, ele é mantido como privado;
03 - Como o evento é privado tem-se uma opção para convidar pessoas, com três opções diferentes: como Organizador, como Revisor e como Autor. Convidando como Organizador ou como revisor, logo após o convite ser eviado, o nome do convidado já aparece na lista, seja de organização ou de revisão;
04 - Ainda na tela de detalhes do evento, tem-se o botão "Adicionar Organizador", onde por email, pode-se convidar vários organizadores;
05 - Da mesma maneira para revisores, com o botão "Adicionar Revisores", pode-se convidar vários revisores por email.

Fluxo do evento público:
O fluxo do evento público segue da mesma maneira que o fluxo de evento privado, com exceção do passo 03 do evento privado, pois como o evento é publico, e todos os usuários podem vê-lo, a opção de convidar pessoas não está presente.
