### ISSUE TITLE
[Funcionalidade] Esqueci minha senha

### ISSUE THREAD

**Issue by zarathon** [npi-ufc-qxd/contest#235]
Implementar a funcionalidade de resetar senha, atraves do uso de Token. Verificar como foi implementado no sistema Prontuário (https://github.com/npi-ufc-qxd/prontuario) e fazer semelhante.

**Comment by mensonones** [comment]
no pacote model do prontuário: Classe Token
no pacote controller do prontuário: Classe Usuario Controller

**Comment by northEXE** [comment]
Teste para a funcionalidade "Esqueci minha senha"

01 - Na tela de login, temos logo abaixo dos campos de login, temos a opção "Esqueci minha senha";
02 - Indo na opção, temos uma tela com o campo de email, para que o usuário possa redefinir a senha;
03 - Logo após, o sistema volta para a tela de login com uma mensagem avisado que logo o usuário receberá um email com as informações para a redefinição de senha;
04 - Indo no email, o usuário recebe um link do sistema para a redefinição da senha;
05 - Acessando o link, vamos para o sistema, em uma tela onde será redefinida a senha e ela será confirmada;
06 - Logo após a redefinição da senha, o sistema volta para a tela de login, avisando que a senha foi redefinida com sucesso;
07 - Usando a nova senha, o sistema segue o seu fluxo normalmente, entrando no dashboard

Segue em anexo as imagens com os passos descritos:


![teste1.png](https://zube.io/files/npi-ufc-qxd/c68a82841c00e50e4cb7b94c65c657fe.png)
Imagem 01 - Tela de login com a opção de redefinir senha

![teste2.png](https://zube.io/files/npi-ufc-qxd/95ecaaf76c4bb29aad498d79e9a6f69e.png)
Imagem 02 - Tela de preenchimento de email para redefinir a senha

![testeerm.png](https://zube.io/files/npi-ufc-qxd/6c26c9b8f12c0ab73ae380c402f7ea00.png)
Imagem 03 - Tela de login com a mensagem informando sobre o recebimento do email

![teste3.png](https://zube.io/files/npi-ufc-qxd/af3c6c3196f4af66e5bb55d4637bb218.png)
Imagem 04 - Email com o link para o sistema

![testeppp.png](https://zube.io/files/npi-ufc-qxd/22812e893fb6a6bdb8a55c25ee4fc8ea.png)
Imagem 05 - Tela de redefinição de senha

![teste4.png](https://zube.io/files/npi-ufc-qxd/7b04c3cbdb95f47e8a12cbaedd1a3586.png)
Imagem 06 - Tela de login com a mensagem informando sobre o sucesso da redefinição da senha

![teste5.png](https://zube.io/files/npi-ufc-qxd/21e65427921c0a46b4837042fd277934.png)
Imagem 07 - Tela inicial do sistema, após entrar com a nova senha
