### ISSUE TITLE
Analise da usabilidade dos organizadores e revisores

### ISSUE THREAD

**Issue by zarathon** [npi-ufc-qxd/contest#241]
Verificar o fluxo, menus e outras funcionalidades para os papéis Organizador e Revisor. Reportar por aqui atraves de imagens e textos.

**Comment by nilsonoliveira9292** [comment]
Card REVISOR:
Ao clicar em Ver mais no dashboard, o usuário é direcionado para a página inicial do revisor, com um menu contendo três itens, Meus Eventos, Eventos Ativos e Eventos inativos.
Ao clicar em Meus Eventos o usuário é direcionado para a página "Meus Eventos" do Organizador, e não para a página "Meus Eventos" do Revisor. O mesmo acontece para os menus "Eventos Ativos" e "Eventos Inativos"
![Dashboard.png](https://zube.io/files/npi-ufc-qxd/7fa7123ae2a40fd68d7590e79e69d189.png)
![Tela eventos ativos.png](https://zube.io/files/npi-ufc-qxd/0d2d49edf334db8392b3505e8c47fc7d.png)
![Tela eventos inativos.png](https://zube.io/files/npi-ufc-qxd/1d65f8d8f0e63200a4795900468940d0.png)
![Tela Meus eventos.png](https://zube.io/files/npi-ufc-qxd/f32b7513e6f0dc314410cd14b18820a7.png)
![Tela revisor.png](https://zube.io/files/npi-ufc-qxd/c689705b528bfe0c983bea97762eea54.png)

**Comment by nilsonoliveira9292** [comment]
Fluxo correto para Revisor:
Após o dashboard o usuário deve ser direcionado para a página Revisor_index que deve ter no menu 2 itens. Revisor_trabalhos e Revisor_avaliar_trabalho
