### ISSUE TITLE
Adicionar link Ir para Dashboard

### ISSUE THREAD

**Issue by zarathon** [npi-ufc-qxd/contest#242]
Adicionar um link no meu superior, caso o usuário tenha o papel USER, adicionar um link nesse menu que o leve para o Dashboard, o título do link deve ser "Ir para Dashboard"

**Comment by northEXE** [comment]
Teste do Dashboard

01 - Entrando no sistema como "USER", temos acesso à tela Dasboard. Como "USER" pode exercer papéis de revisor, organoizador e autor, temos três cards, cada um mostrando informações sobre o que o usuário está ministrando, seja uma revisão de trabalho, organizando um evento e/ou sendo autor de um trabalho;

02 -  Observando o primeiro card, que é de revisão de trabalhos, podemos ver o espaço onde ficam os trabalhos revisados pelo usuário. A opção "Ver Mais" expande as informações sobre os trabalhos revisados pelo usuário;
    2.1 - Abrindo o card, entra-se na tela de revisor, onde devem ser mostrados os trabalhos quais o usuário está revisando. Porém, neste teste os trabalhos revisados não aparecem, aparecendo o label "Lista de Eventos", e a tela em branco;

03 - O segundo card mostram os eventos quais o usuário está organizando. A opção "Ver Mais" expande as informações sobre os trabalhos organizados pelo usuário;

04 - O terceiro card, que fica mais abaixo, mostram os eventos quais o usuário pode participar como autor. Paricipando do evento como autor, o usuário irá submeter o trabalho que vai apresentar; Logo após confirmar a participação no evento como autor, são mostrados os detalhes do evento;

Obs: Não foi possível ver os trabalhos revisados pelo usuário na opção de "Ver Mais". Deveria aparecer uma lista com os trabalhos revisados, porém, a tela que abre é a tela de lista de evntos, porém está vazia;

Em um dos testes, tentei a participação, porém o sistema apresentou um erro. Logo após, voltando ao Dahboard, o usuário irá se deparar com uma contradição: o usuário está e não está participando de um evento.

Da mesma maneira que a primeira observação, quando se selciona a opção "Ver mais" no card de organização, vamos para lista de eventos estando vazia.

Segue em anexo as imagens com os passos descritos:
