### ISSUE TITLE
Corrigir Selecionar Responsável Para Seção

### ISSUE THREAD

**Issue by CarlosQuixada** [npi-ufc-qxd/contest#248]
Na página cadastrar seção não está mostrando quem pode ser selecionado pra ser rsponsável

**Comment by northEXE** [comment]
Teste para seleção de pessoas no cadastro de uma seção.

01 - Entrando no sistema como "USER", no card de Organizador, é selecionada a opção "Ver mais";
02 - Na tela que vem após clicar na opção ver mais, temos a opção "Visualizar Seções";
03 - Na opção de visualizações de seções, como não há nenhuma seção criada, será criada uma nova;
04 - Na opção Cadastrar seção, o sistema vai para de cadastrar seção, com os campos necessários para o cadastro;
05 - O problema anterior com o cadastro da seção, era achar pessoas para ser responsável. Aqui o problema foi sanado;
06 - Logo após o cadastro, podemos ver o card com a seção cadastrada

Obs:
Quando vamos na opção de "Ver mais" no card da seção, dá um erro de permissão de acesso, da mesma maneira em deletar seção;

Segue em anexo as imagens com os passos descritos:

![secao1.png](https://zube.io/files/npi-ufc-qxd/554b1f4a8a30c327caeba12fa6c0fbe2.png)
Imagem 01 - Tela de dashboard do usuário

![secao2.png](https://zube.io/files/npi-ufc-qxd/129d531661dd2dd168b0646f9740646a.png)
Imagem 02 - Tela de detalhes de organização

![secao3.png](https://zube.io/files/npi-ufc-qxd/e4abf5307868ae6c078bd258d1cca110.png)
Imagem 03 - Tela de cadastro de seção com seleção de pessoa responsável

![secao4.png](https://zube.io/files/npi-ufc-qxd/0b778243028b93e77e4e618a745026af.png)
Imagem 04 - Card com o sucesso da criação da seção

![secao erro.png](https://zube.io/files/npi-ufc-qxd/5998bf4ba9100d9e14b5757a757eb735.png)
Imagem 05 - Tela de erro ao tentar deletar ou ver detalhes da seção
